# Generated by Django 4.1.2 on 2022-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stamp',
            field=models.IntegerField(default=0),
        ),
    ]
