# Generated by Django 3.2.16 on 2022-12-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stamp',
            field=models.IntegerField(default=0),
        ),
    ]
