# Generated by Django 4.1.2 on 2022-12-15 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Use_by',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('D', 'Drink'), ('I', 'Icecream'), ('C', 'Cake'), ('Muffin', 'M'), ('Donut', 'Do'), ('Other', 'O')], default='Other', max_length=12),
        ),
    ]
