# Generated by Django 3.2.16 on 2022-12-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('D', 'Drink'), ('I', 'Icecream'), ('C', 'Cake'), ('Muffin', 'M'), ('Donut', 'Do'), ('Other', 'O')], default='Other', max_length=12),
        ),
    ]
