# Generated by Django 4.1.2 on 2022-11-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Drink', 'D'), ('Icecream', 'I'), ('Cake', 'C'), ('Muffin', 'M'), ('Donut', 'Do'), ('Other', 'O')], default='Other', max_length=12),
        ),
        migrations.CreateModel(
            name='Table_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField()),
                ('order', models.ManyToManyField(to='menu.menu')),
            ],
        ),
    ]
