# Generated by Django 4.1.2 on 2022-11-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_type_table_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_order',
            old_name='order',
            new_name='ordermenu',
        ),
        migrations.RenameField(
            model_name='table_order',
            old_name='table',
            new_name='table_number',
        ),
    ]
