# Generated by Django 3.2.16 on 2022-12-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_order',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
