# Generated by Django 4.1.2 on 2022-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_table_use_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('D', 'Drink'), ('I', 'Icecream'), ('C', 'Cake'), ('M', 'Muffin'), ('Do', 'Donut'), ('O', 'Other')], default='Other', max_length=12),
        ),
    ]
