# Generated by Django 4.1.2 on 2022-11-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_table_alter_table_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_order',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
